### PR TITLE
fixing a chain resume issue

### PR DESCRIPTION
**Pull request by jeremy-baier**
See issue [53](https://github.com/nanograv/PTMCMCSampler/issues/53).

### CODE REVIEW

**Comment by kdolum** [comment]
Jeremy, did you verify that with this change it works to resume both when only one sample has been saved and when there are more than that?

**Comment by vhaasteren** [comment]
Thank you for figuring this out, @jeremy-baier! Please confirm that it works for the case that @kdolum suggests, and then we can merge.

**Comment by jeremy-baier** [comment]
Thanks for the reminder!
I can confirm that this does fix the issue I was seeing.
When I replicate the scenario, I get this message and the sampler proceeds to sample:
`Resuming with 1 samples from file representing 1 original samples`
Since it just picks up sampling from the original 1 sample, there shouldn’t be any issues with `isave` or `ithin`.
Thanks for your help with this, Ken!!

**Comment by kdolum** [comment]
Thanks, @jeremy-baier.  Did you also verify that it works in the case where it worked before where there's not just one sample?  I've no reason to think it would fail, but it's good to the be careful.

**Comment by jeremy-baier** [comment]
I can confirm that it does:
`Resuming with 2201 samples from file representing 22001 original samples`
And I just checked that it will work with an empty chain file and no chain file.

**Review by kdolum — APPROVED** [review]
Looks good.

**Review by vhaasteren — COMMENTED** [review]
Looks good

**Pull request merged**
