### PR TITLE
Fix sample-counting and resuming bugs

### PR DESCRIPTION
**Pull request by kdolum**
Fix bugs #10 and #20 as described in #10.  In the usual case where `Niter` is a multiple of `isave`, all computed samples will be written out.  The run can be resumed with some larger `Niter` and the samples will be correctly counted.  If `Niter` is a multiple of `thin` but not of `isave`, the partial block of samples will be written at the end.  In this case you cannot resume without deleting this partial block by hand.  If `Niter` is not a multiple of `thin`, the extra samples will be computed but not written.of
Progress reports after resuming give the percentage of the new samples that have been computed, as well as the percentage of the total.

### CODE REVIEW

**Comment by kdolum** [comment]
I tested many cases involving various values of `Niter`, but I don't have any test case that uses multiple threads.  It would be good to test that before merging.

**Comment by kdolum** [comment]
There was a bug involving parole tempering in which partial blocks did not get written out except in the cold chain.  Now that is fixed and I have tested it with multiple threads and everything seems to work.

**Comment by vhaasteren** [comment]
@kdolum, the works looks good. However, the integration tests are failing at the moment for reasons not related to your PR. I think it's good policy to fix those first before merging. Let me first have a look at that first.

You also write you haven't been able to test with MPI. Is that still correct? I saw your message regarding thermodynamic integration the other day, so perhaps you have been looking into this.

The tests do run locally on my workstation, so that's at least a good sign.

**Comment by kdolum** [comment]
I did test it with MPI and all seems well.

**Comment by vhaasteren** [comment]
This PR depends on #44 to pass the integration tests. So that one first needs to be handled before we can merge this PR

**Review by vhaasteren — APPROVED** [review]
Looks good

**Pull request merged**
